@plr = player()


@hero = associative_array(
            'name': '§4S§ccarle§4t §4W§citc§4h',
            'class': 'scarletwitch',
            'sig': 'p/ghGFc0ZmrQIMzsYP3lUC7f0aX/u86/rH7JhPGsA3yvkqlrBzJckChq4oTdRtq1mxxr9tcCkDH756yhMUsjlc+/2P2F1Cjh1Bs0uqY9E/MqaYRuwO8swQ40H/wSPZZ2eKEGdHrxoyHFNcvkHLE9vx+z9W5Gel2zuVM48Mu3FE42JNUIJ1D+2R6XQTsHsTHAlNNhjUQ3lGzjHUXq/xF1M/IVA7Hog/9cV7BP2wvM5eDHS7PpCP/JtZ9G1hm58nvyJtbbYvZpOXh6OTbaUxsXu+XG2VK3X+A9dn1lQz2LsnQm1lMnrLLX+ADkUAtd9pQ1H1kIjrlGSr3WiM9xwT6EbBTl1HigJUECk0eX41gEPHCMBVrgxoC+zBq62ONGEs3b0Ziw4qKZGfHP4Aa44o1oR557nei+Zo/TJG5TjTPEuET3MM5JLb3kEtIwAbKNgH8I9zDVtFkxbv6dkLWCiu53SDCbjpWdDlOirQ4xggq9QZHl/T5ExTZeH4MqmBM+JW3YA9A0Mk1yjs7fqPS1C+a5D2I8Y2RV3cDORQK7sQl9Qe4opr+yt1PMM73s40wakotEwZYNqFSomeaohfwFnRuBou11W66Iti9ODLXI5p6FhiP77cxmzmN70GjVv2U3zp0M9gHkbcc8Tkuxw+Y7BOmgzMTAcYJMIi+e5xdw+KMXC7c=',
            'val': 'eyJ0aW1lc3RhbXAiOjE0OTExODIwMDU2MjMsInByb2ZpbGVJZCI6IjljYjA3YjgyNGQyZjQ0NmZiMTk0NGY4M2RlZTFlMDJmIiwicHJvZmlsZU5hbWUiOiJUb29GbHVmZnkiLCJzaWduYXR1cmVSZXF1aXJlZCI6dHJ1ZSwidGV4dHVyZXMiOnsiU0tJTiI6eyJtZXRhZGF0YSI6eyJtb2RlbCI6InNsaW0ifSwidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9lZTZlMTU4ZTkxNTUzYmVjODQ0ZjE5NmFhZjg3Y2RjNWQyNmMxMzc1MjcwZjA3MDU4Mzk0NDNmZDY2ZjU1In19fQ==',
            'trail': '',
            'op': 'false',
            'speech': "Being a hero is hard. Deal with it.",
            'powers': array(
                "/buff",
                "/hover on",
                "/hover off"
                "/fly"
                "/tp"
                "/tphere"
            ),
            'buffs': array(
                "/shot give ". @plr ." redenergybeam"                
            )
        )
